### PR TITLE
Develop steamy32

### PR DESCRIPTION
**Pull request by jnthbdn**

### CODE REVIEW

**Comment by jnthbdn** [comment]
Le CI (pas à nous) plante avec l'erreur suivante:
```
[10965/11607] Generating stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld
FAILED: stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld /home/runner/work/DAPLink/DAPLink/projectfiles/cmake_gcc_arm/stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld 
cd /home/runner/work/DAPLink/DAPLink/projectfiles/cmake_gcc_arm && /home/runner/gcc-arm-none-eabi-10.3.202110-linux/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-gcc -E -x c -P -MMD -I/home/runner/work/DAPLink/DAPLink/source/usb -I/home/runner/work/DAPLink/DAPLink/source/daplink/cmsis-dap -I/home/runner/work/DAPLink/DAPLink/source/daplink/drag-n-drop -I/home/runner/work/DAPLink/DAPLink/source/daplink/usb2uart -I/home/runner/work/DAPLink/DAPLink/source/daplink/settings -I/home/runner/work/DAPLink/DAPLink/source/daplink -I/home/runner/work/DAPLink/DAPLink/source/daplink/interface -I/home/runner/work/DAPLink/DAPLink/source/cmsis-core -I/home/runner/work/DAPLink/DAPLink/source/hic_hal -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/cmsis-driver -I/home/runner/work/DAPLink/DAPLink/source/target -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb/cmsis -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb/STM32F1xx_HAL_Driver -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb/STM32F1xx_HAL_Driver/Inc -I/home/runner/work/DAPLink/DAPLink/source/rtos2/Include -I/home/runner/work/DAPLink/DAPLink/source/rtos2/RTX/Include -DDAPLINK_VERSION=259 -DMSC_ENDPOINT -DCDC_ENDPOINT -DWEBUSB_INTERFACE -DWINUSB_INTERFACE -DDRAG_N_DROP_SUPPORT -DDAPLINK_IF -DDAPLINK_BUILD_KEY=0x9B939E8F -DOS_TICK_FREQ=100 -DINTERFACE_STM32F103XB -DUSE_HAL_DRIVER -DSTM32F103xB -DDAPLINK_HIC_ID=0x97969908 -D__packed=__packed -DDAPLINK_NO_ASSERT_FILENAMES -DOS_CLOCK=72000000 -DMAIN_TASK_STACK=960 -DHID_ENDPOINT "-DUSB_PROD_STR=\"STeaMi CMSIS-DAP\"" "-DCMSIS_DAP_PRODUCT_NAME=\"\\" "STeaMi\\\"\"\"" -DHAL_I2C_MODULE_ENABLED -DHAL_SPI_MODULE_ENABLED -D__PROGRAM_START -o /home/runner/work/DAPLink/DAPLink/projectfiles/cmake_gcc_arm/stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld /home/runner/work/DAPLink/DAPLink/source/daplink/daplink.ld
arm-none-eabi-gcc: error: STeaMi\""": No such file or directory
```

Visiblement il s'agit plus un problème d'échappement de caractère que d'un problème venant de notre coté. Je n'ai pas cette erreur sur ma machine en compilant après un clean complet.

**Comment by nedseb** [comment]
> Le CI (pas à nous) plante avec l'erreur suivante:
> 
> ```
> [10965/11607] Generating stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld
> FAILED: stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld /home/runner/work/DAPLink/DAPLink/projectfiles/cmake_gcc_arm/stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld 
> cd /home/runner/work/DAPLink/DAPLink/projectfiles/cmake_gcc_arm && /home/runner/gcc-arm-none-eabi-10.3.202110-linux/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-gcc -E -x c -P -MMD -I/home/runner/work/DAPLink/DAPLink/source/usb -I/home/runner/work/DAPLink/DAPLink/source/daplink/cmsis-dap -I/home/runner/work/DAPLink/DAPLink/source/daplink/drag-n-drop -I/home/runner/work/DAPLink/DAPLink/source/daplink/usb2uart -I/home/runner/work/DAPLink/DAPLink/source/daplink/settings -I/home/runner/work/DAPLink/DAPLink/source/daplink -I/home/runner/work/DAPLink/DAPLink/source/daplink/interface -I/home/runner/work/DAPLink/DAPLink/source/cmsis-core -I/home/runner/work/DAPLink/DAPLink/source/hic_hal -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/cmsis-driver -I/home/runner/work/DAPLink/DAPLink/source/target -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb/cmsis -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb/STM32F1xx_HAL_Driver -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb/STM32F1xx_HAL_Driver/Inc -I/home/runner/work/DAPLink/DAPLink/source/rtos2/Include -I/home/runner/work/DAPLink/DAPLink/source/rtos2/RTX/Include -DDAPLINK_VERSION=259 -DMSC_ENDPOINT -DCDC_ENDPOINT -DWEBUSB_INTERFACE -DWINUSB_INTERFACE -DDRAG_N_DROP_SUPPORT -DDAPLINK_IF -DDAPLINK_BUILD_KEY=0x9B939E8F -DOS_TICK_FREQ=100 -DINTERFACE_STM32F103XB -DUSE_HAL_DRIVER -DSTM32F103xB -DDAPLINK_HIC_ID=0x97969908 -D__packed=__packed -DDAPLINK_NO_ASSERT_FILENAMES -DOS_CLOCK=72000000 -DMAIN_TASK_STACK=960 -DHID_ENDPOINT "-DUSB_PROD_STR=\"STeaMi CMSIS-DAP\"" "-DCMSIS_DAP_PRODUCT_NAME=\"\\" "STeaMi\\\"\"\"" -DHAL_I2C_MODULE_ENABLED -DHAL_SPI_MODULE_ENABLED -D__PROGRAM_START -o /home/runner/work/DAPLink/DAPLink/projectfiles/cmake_gcc_arm/stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld /home/runner/work/DAPLink/DAPLink/source/daplink/daplink.ld
> arm-none-eabi-gcc: error: STeaMi\""": No such file or directory
> ```
> 
> Visiblement il s'agit plus un problème d'échappement de caractère que d'un problème venant de notre coté. Je n'ai pas cette erreur sur ma machine en compilant après un clean complet.

Visiblement c'est la variable DCMSIS_DAP_PRODUCT_NAME qui est étrange. Tu sais si on a fait un truc de spécial avec ?

**Comment by jnthbdn** [comment]
> > Le CI (pas à nous) plante avec l'erreur suivante:
> > ```
> > [10965/11607] Generating stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld
> > FAILED: stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld /home/runner/work/DAPLink/DAPLink/projectfiles/cmake_gcc_arm/stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld 
> > cd /home/runner/work/DAPLink/DAPLink/projectfiles/cmake_gcc_arm && /home/runner/gcc-arm-none-eabi-10.3.202110-linux/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-gcc -E -x c -P -MMD -I/home/runner/work/DAPLink/DAPLink/source/usb -I/home/runner/work/DAPLink/DAPLink/source/daplink/cmsis-dap -I/home/runner/work/DAPLink/DAPLink/source/daplink/drag-n-drop -I/home/runner/work/DAPLink/DAPLink/source/daplink/usb2uart -I/home/runner/work/DAPLink/DAPLink/source/daplink/settings -I/home/runner/work/DAPLink/DAPLink/source/daplink -I/home/runner/work/DAPLink/DAPLink/source/daplink/interface -I/home/runner/work/DAPLink/DAPLink/source/cmsis-core -I/home/runner/work/DAPLink/DAPLink/source/hic_hal -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/cmsis-driver -I/home/runner/work/DAPLink/DAPLink/source/target -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb/cmsis -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb/STM32F1xx_HAL_Driver -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb/STM32F1xx_HAL_Driver/Inc -I/home/runner/work/DAPLink/DAPLink/source/rtos2/Include -I/home/runner/work/DAPLink/DAPLink/source/rtos2/RTX/Include -DDAPLINK_VERSION=259 -DMSC_ENDPOINT -DCDC_ENDPOINT -DWEBUSB_INTERFACE -DWINUSB_INTERFACE -DDRAG_N_DROP_SUPPORT -DDAPLINK_IF -DDAPLINK_BUILD_KEY=0x9B939E8F -DOS_TICK_FREQ=100 -DINTERFACE_STM32F103XB -DUSE_HAL_DRIVER -DSTM32F103xB -DDAPLINK_HIC_ID=0x97969908 -D__packed=__packed -DDAPLINK_NO_ASSERT_FILENAMES -DOS_CLOCK=72000000 -DMAIN_TASK_STACK=960 -DHID_ENDPOINT "-DUSB_PROD_STR=\"STeaMi CMSIS-DAP\"" "-DCMSIS_DAP_PRODUCT_NAME=\"\\" "STeaMi\\\"\"\"" -DHAL_I2C_MODULE_ENABLED -DHAL_SPI_MODULE_ENABLED -D__PROGRAM_START -o /home/runner/work/DAPLink/DAPLink/projectfiles/cmake_gcc_arm/stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld /home/runner/work/DAPLink/DAPLink/source/daplink/daplink.ld
> > arm-none-eabi-gcc: error: STeaMi\""": No such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Visiblement il s'agit plus un problème d'échappement de caractère que d'un problème venant de notre coté. Je n'ai pas cette erreur sur ma machine en compilant après un clean complet.
> 
> Visiblement c'est la variable DCMSIS_DAP_PRODUCT_NAME qui est étrange. Tu sais si on a fait un truc de spécial avec ?

Il me semble que cette variable est responsable du nom afficher lorsque tu listes les target (avec `pyocd list` par exemple)
```
 $ pyocd list                    
  #   Probe/Board            Unique ID                                          Target           
-------------------------------------------------------------------------------------------------
  0   Arm STeaMi CMSIS-DAP   08390001066bff485753667187195629a5a5a5a597969908   ✔︎ stm32wb55rgvx  
  ```
  
  La macro est utilisée ici :
  https://github.com/letssteam/DAPLink/blob/bc0cb40bcdc9ba09142793d69ae4072c216cf929/source/daplink/cmsis-dap/dap_strings.h#L26
  
  https://github.com/letssteam/DAPLink/blob/bc0cb40bcdc9ba09142793d69ae4072c216cf929/source/daplink/cmsis-dap/dap_strings.h#L62

**Comment by nedseb** [comment]
> > > Le CI (pas à nous) plante avec l'erreur suivante:
> > > ```
> > > [10965/11607] Generating stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld
> > > FAILED: stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld /home/runner/work/DAPLink/DAPLink/projectfiles/cmake_gcc_arm/stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld 
> > > cd /home/runner/work/DAPLink/DAPLink/projectfiles/cmake_gcc_arm && /home/runner/gcc-arm-none-eabi-10.3.202110-linux/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-gcc -E -x c -P -MMD -I/home/runner/work/DAPLink/DAPLink/source/usb -I/home/runner/work/DAPLink/DAPLink/source/daplink/cmsis-dap -I/home/runner/work/DAPLink/DAPLink/source/daplink/drag-n-drop -I/home/runner/work/DAPLink/DAPLink/source/daplink/usb2uart -I/home/runner/work/DAPLink/DAPLink/source/daplink/settings -I/home/runner/work/DAPLink/DAPLink/source/daplink -I/home/runner/work/DAPLink/DAPLink/source/daplink/interface -I/home/runner/work/DAPLink/DAPLink/source/cmsis-core -I/home/runner/work/DAPLink/DAPLink/source/hic_hal -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/cmsis-driver -I/home/runner/work/DAPLink/DAPLink/source/target -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb/cmsis -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb/STM32F1xx_HAL_Driver -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb/STM32F1xx_HAL_Driver/Inc -I/home/runner/work/DAPLink/DAPLink/source/rtos2/Include -I/home/runner/work/DAPLink/DAPLink/source/rtos2/RTX/Include -DDAPLINK_VERSION=259 -DMSC_ENDPOINT -DCDC_ENDPOINT -DWEBUSB_INTERFACE -DWINUSB_INTERFACE -DDRAG_N_DROP_SUPPORT -DDAPLINK_IF -DDAPLINK_BUILD_KEY=0x9B939E8F -DOS_TICK_FREQ=100 -DINTERFACE_STM32F103XB -DUSE_HAL_DRIVER -DSTM32F103xB -DDAPLINK_HIC_ID=0x97969908 -D__packed=__packed -DDAPLINK_NO_ASSERT_FILENAMES -DOS_CLOCK=72000000 -DMAIN_TASK_STACK=960 -DHID_ENDPOINT "-DUSB_PROD_STR=\"STeaMi CMSIS-DAP\"" "-DCMSIS_DAP_PRODUCT_NAME=\"\\" "STeaMi\\\"\"\"" -DHAL_I2C_MODULE_ENABLED -DHAL_SPI_MODULE_ENABLED -D__PROGRAM_START -o /home/runner/work/DAPLink/DAPLink/projectfiles/cmake_gcc_arm/stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld /home/runner/work/DAPLink/DAPLink/source/daplink/daplink.ld
> > > arm-none-eabi-gcc: error: STeaMi\""": No such file or directory
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Visiblement il s'agit plus un problème d'échappement de caractère que d'un problème venant de notre coté. Je n'ai pas cette erreur sur ma machine en compilant après un clean complet.
> > 
> > 
> > Visiblement c'est la variable DCMSIS_DAP_PRODUCT_NAME qui est étrange. Tu sais si on a fait un truc de spécial avec ?
> 
> Il me semble que cette variable est responsable du nom afficher lorsque tu listes les target (avec `pyocd list` par exemple)
> 
> ```
>  $ pyocd list                    
>   #   Probe/Board            Unique ID                                          Target           
> -------------------------------------------------------------------------------------------------
>   0   Arm STeaMi CMSIS-DAP   08390001066bff485753667187195629a5a5a5a597969908   ✔︎ stm32wb55rgvx  
> ```
> 
> La macro est utilisée ici :
> 
> https://github.com/letssteam/DAPLink/blob/bc0cb40bcdc9ba09142793d69ae4072c216cf929/source/daplink/cmsis-dap/dap_strings.h#L26
> 
> https://github.com/letssteam/DAPLink/blob/bc0cb40bcdc9ba09142793d69ae4072c216cf929/source/daplink/cmsis-dap/dap_strings.h#L62

Et on ne définit pas une chaine de notre coté que permet de construire cette variable ? J'ai l'impression qu'il y a des quotes dans des quotes qui sont étrangement échapés par d'autres quotes

**Comment by jnthbdn** [comment]
> > > > Le CI (pas à nous) plante avec l'erreur suivante:
> > > > ```
> > > > [10965/11607] Generating stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld
> > > > FAILED: stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld /home/runner/work/DAPLink/DAPLink/projectfiles/cmake_gcc_arm/stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld 
> > > > cd /home/runner/work/DAPLink/DAPLink/projectfiles/cmake_gcc_arm && /home/runner/gcc-arm-none-eabi-10.3.202110-linux/gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-gcc -E -x c -P -MMD -I/home/runner/work/DAPLink/DAPLink/source/usb -I/home/runner/work/DAPLink/DAPLink/source/daplink/cmsis-dap -I/home/runner/work/DAPLink/DAPLink/source/daplink/drag-n-drop -I/home/runner/work/DAPLink/DAPLink/source/daplink/usb2uart -I/home/runner/work/DAPLink/DAPLink/source/daplink/settings -I/home/runner/work/DAPLink/DAPLink/source/daplink -I/home/runner/work/DAPLink/DAPLink/source/daplink/interface -I/home/runner/work/DAPLink/DAPLink/source/cmsis-core -I/home/runner/work/DAPLink/DAPLink/source/hic_hal -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/cmsis-driver -I/home/runner/work/DAPLink/DAPLink/source/target -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb/cmsis -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb/STM32F1xx_HAL_Driver -I/home/runner/work/DAPLink/DAPLink/source/hic_hal/stm32/stm32f103xb/STM32F1xx_HAL_Driver/Inc -I/home/runner/work/DAPLink/DAPLink/source/rtos2/Include -I/home/runner/work/DAPLink/DAPLink/source/rtos2/RTX/Include -DDAPLINK_VERSION=259 -DMSC_ENDPOINT -DCDC_ENDPOINT -DWEBUSB_INTERFACE -DWINUSB_INTERFACE -DDRAG_N_DROP_SUPPORT -DDAPLINK_IF -DDAPLINK_BUILD_KEY=0x9B939E8F -DOS_TICK_FREQ=100 -DINTERFACE_STM32F103XB -DUSE_HAL_DRIVER -DSTM32F103xB -DDAPLINK_HIC_ID=0x97969908 -D__packed=__packed -DDAPLINK_NO_ASSERT_FILENAMES -DOS_CLOCK=72000000 -DMAIN_TASK_STACK=960 -DHID_ENDPOINT "-DUSB_PROD_STR=\"STeaMi CMSIS-DAP\"" "-DCMSIS_DAP_PRODUCT_NAME=\"\\" "STeaMi\\\"\"\"" -DHAL_I2C_MODULE_ENABLED -DHAL_SPI_MODULE_ENABLED -D__PROGRAM_START -o /home/runner/work/DAPLink/DAPLink/projectfiles/cmake_gcc_arm/stm32f103xb_steami32_if/build/stm32f103xb_steami32_if.ld /home/runner/work/DAPLink/DAPLink/source/daplink/daplink.ld
> > > > arm-none-eabi-gcc: error: STeaMi\""": No such file or directory
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Visiblement il s'agit plus un problème d'échappement de caractère que d'un problème venant de notre coté. Je n'ai pas cette erreur sur ma machine en compilant après un clean complet.
> > > 
> > > 
> > > Visiblement c'est la variable DCMSIS_DAP_PRODUCT_NAME qui est étrange. Tu sais si on a fait un truc de spécial avec ?
> > 
> > 
> > Il me semble que cette variable est responsable du nom afficher lorsque tu listes les target (avec `pyocd list` par exemple)
> > ```
> >  $ pyocd list                    
> >   #   Probe/Board            Unique ID                                          Target           
> > -------------------------------------------------------------------------------------------------
> >   0   Arm STeaMi CMSIS-DAP   08390001066bff485753667187195629a5a5a5a597969908   ✔︎ stm32wb55rgvx  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > La macro est utilisée ici :
> > https://github.com/letssteam/DAPLink/blob/bc0cb40bcdc9ba09142793d69ae4072c216cf929/source/daplink/cmsis-dap/dap_strings.h#L26
> > 
> > https://github.com/letssteam/DAPLink/blob/bc0cb40bcdc9ba09142793d69ae4072c216cf929/source/daplink/cmsis-dap/dap_strings.h#L62
> 
> Et on ne définit pas une chaine de notre coté que permet de construire cette variable ? J'ai l'impression qu'il y a des quotes dans des quotes qui sont étrangement échapés par d'autres quotes

Je viens de faire un commit pour essayer de ne plus avoir ce pb de quote.

**Comment by jnthbdn** [comment]
Bon je viens de faire plusieurs test pour éviter les échappement d'échappement, mais ça commence à me gonfler leurs système... Le YAML lut par un autre truc pour ensuite le tranformer en commande c'est assez pourri...

En plus dans la doc il précise bien que c'"est possible de le modifier comme les autres...
https://github.com/letssteam/DAPLink/blob/develop/docs/string_customization.md

Donc j'ai déplace le define dans le fichier principal de notre target... c'est pas super propre mais ça marche...
https://github.com/letssteam/DAPLink/blob/b2a5224aa9218eac55d1640fa0eb8bf30d0f4bf2/source/board/steami/steami32.c#L76

**Pull request merged**
